#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        a = 2
        b = 3
        a + b
        return (r)
    except NameError:
        print(message)
